new build system completely decoupled from Mozilla

diff --git a/util/xptgen b/util/xptgen
--- a/util/xptgen
+++ b/util/xptgen
@@ -8,43 +8,57 @@
 ## Wrapper script for creating xpt files from idl files
 
 # Parameters
-# 1 - mozilla top directory
-# 2 - source dir
-# 3 - depth (relative path to top level dir)
+# 1 - python directory
+# 2 - additional interfaces dir
+# 3 - Directory of typelib.py
+# 4 - DIST directory
 # 4 .. n - idl file name
 
 
-mkdir -p .deps _xpidlgen
+mkdir -p _xpidlgen
 
 PYTHON=$1
-TOPDIR=$2
-SRCDIR=$3
-DEPTH=$4
+SDK_DIR=$2
+TYPELIB_DIR=$3
+DIST=$4
 
 shift 4
 
+XPTFILES=""
+
 while [ $# -gt 0 ]; do
-  XPTFILE=$1
-  XPTBASE=`basename $1 | sed s/.xpt$//`
-  HDRFILE=`echo $1 | sed s/.xpt$/.h/`
+  XPIFILE=$1
+  XPTFILE=`basename $1 | sed s/.idl$/.xpt/`
+  XPTFILES="$XPTFILES  _xpidlgen/$XPTFILE"
 
-  ${PYTHON} -u ${TOPDIR}/mozilla/config/pythonpath.py \
-    -I${TOPDIR}/mozilla/xpcom/typelib/xpt/tools \
-    ${DEPTH}/mozilla/dist/sdk/bin/typelib.py \
-    -I${TOPDIR}/mailnews/extensions/enigmail/public \
-    -I../../../../mozilla/dist/idl \
-    ${SRCDIR}/${XPTBASE}.idl \
-    -d .deps/${XPTBASE}.pp \
-    -o ${XPTFILE}
+  ${PYTHON} \
+    ${TYPELIB_DIR}/typelib.py \
+    -I${SDK_DIR} \
+    -o _xpidlgen/${XPTFILE} \
+    ${XPIFILE}
 
-  ${PYTHON} -u ${TOPDIR}/mozilla/config/pythonpath.py \
-    -I${TOPDIR}/mozilla/xpcom/typelib/xpt/tools \
-    ${DEPTH}/mozilla/dist/sdk/bin/header.py \
-    -I${TOPDIR}/mailnews/extensions/enigmail/public \
-    -I../../../../mozilla/dist/idl \
-    ${SRCDIR}/${XPTBASE}.idl \
-    -d .deps/${XPTBASE}.pp \
-    -o ${HDRFILE}
+  if [ $? -ne 0 ]; then
+    echo "** Could not create xpt file for $XPIFILE"
+    exit 1
+  fi
+
+#   ${PYTHON} -u ${TOPDIR}/mozilla/config/pythonpath.py \
+#     -I${TOPDIR}/mozilla/xpcom/typelib/xpt/tools \
+#     ${DEPTH}/mozilla/dist/sdk/bin/header.py \
+#     -I${TOPDIR}/mailnews/extensions/enigmail/public \
+#     -I../../../../mozilla/dist/idl \
+#     ${SRCDIR}/${XPTBASE}.idl \
+#     -d .deps/${XPTBASE}.pp \
+#     -o ${HDRFILE}
 
   shift
 done
+
+mkdir -p ${DIST}/components
+
+${PYTHON} \
+  ${TYPELIB_DIR}/xpt.py \
+  link \
+  ${DIST}/components/enigmail.xpt \
+  $XPTFILES
+
